name: CI
on:
  push: { branches: ["main"] }
  pull_request: { branches: ["main"] }

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.11" }
      - name: Install
        run: |
          python -m pip install --upgrade pip
          pip install -e ".[dev]"
      - name: Lint/Format/Type
        run: |
          ruff check .
          ruff format --check .
          mypy
      - name: Tests
        run: pytest -q
      - name: Demo smoke (cart-pole 10s)
        run: |
          python -m benchmarks.run_cartpole --controller scfd --steps 1000 --episodes 1 --viz none